export enum NotificationsTypes {
  CREATE_MESSAGE = "CREATE_MESSAGE",
  DELETE_MESSAGE = "DELETE_MESSAGE",
  UPDATE_MESSAGE = "UPDATE_MESSAGE",
  CREATE_CHAT = "CREATE_CHAT",
  UPDATE_CHAT = "UPDATE_CHAT",
}
